#!/bin/bash

# find out where is program being run
SOURCE="${BASH_SOURCE[0]}"
DIR="$(cd -P "$(dirname "${SOURCE}")" && pwd)"

TOOL="${DIR}/pathstrip.py"

TARGET="$1"
PREFIX="$2"

TMP="${TARGET}.pathstrip-tmp"
function cleanup() {
    rm -f ${TMP}
}

trap cleanup EXIT

set -e
cp -a "${TARGET}" "${TMP}"
"${TOOL}" "${TMP}" $(objdump "${TMP}" --section-headers \
    | gawk '/\.rodata/ { print "0x"$6, "0x"$3}') "${PREFIX}"
mv "${TMP}" "${TARGET}"
