# - Try to find NVONNXPARSER
# Once done, this will define
#
#  NVONNXPARSER_FOUND - system has NVONNXPARSER
#  NVONNXPARSER_INCLUDE_DIRS - the NVONNXPARSER include directories
#  NVONNXPARSER_LIBRARIES - link these to use NVONNXPARSER

find_path(NVONNXPARSER_INCLUDE_DIR NvInfer.h
  HINTS $ENV{TENSORRT_ROOT} ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES include)

find_library(NVONNXPARSER_LIBRARY nvonnxparser
  HINTS $ENV{TENSORRT_ROOT} ${TENSORRT_BUILD} ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES lib lib64 lib/x64)

set(NVONNXPARSER_INCLUDE_DIRS ${NVONNXPARSER_INCLUDE_DIR})
list(APPEND NVONNXPARSER_LIBRARIES ${NVONNXPARSER_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(nvonnxparser DEFAULT_MSG
  NVONNXPARSER_LIBRARIES
  NVONNXPARSER_INCLUDE_DIRS)
mark_as_advanced(NVONNXPARSER_INCLUDE_DIRS NVONNXPARSER_LIBRARIES)
