# Create custom build type: Customerrelease

# cloned from Release
set(CMAKE_CXX_FLAGS_CUSTOMERRELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
set(CMAKE_C_FLAGS_CUSTOMERRELEASE "${CMAKE_C_FLAGS_RELEASE}")
set(CMAKE_EXE_LINKER_FLAGS_CUSTOMERRELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE}")

# clone definitions from Release and add custom definitions
get_property(defs DIRECTORY PROPERTY COMPILE_DEFINITIONS_RELEASE)
set_property(DIRECTORY PROPERTY COMPILE_DEFINITIONS_CUSTOMERRELEASE ${defs}
  BUILDSYS_CUSTOMER_BUILD=1)

set(BUILDSYS_CUSTOMER_BUILD_CUSTOMERRELEASE TRUE)
