# Create custom build type: Customerdebug

# cloned from Debug
set(CMAKE_CXX_FLAGS_CUSTOMERDEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
set(CMAKE_C_FLAGS_CUSTOMERDEBUG "${CMAKE_C_FLAGS_DEBUG}")
set(CMAKE_EXE_LINKER_FLAGS_CUSTOMERDEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")

# clone definitions from Debug and add custom definitions
get_property(defs DIRECTORY PROPERTY COMPILE_DEFINITIONS_DEBUG)
set_property(DIRECTORY PROPERTY COMPILE_DEFINITIONS_CUSTOMERDEBUG ${defs}
  BUILDSYS_CUSTOMER_BUILD=1)

set(BUILDSYS_CUSTOMER_BUILD_CUSTOMERDEBUG TRUE)
