#!/usr/bin/env python2
# -*- python -*-

import sys
import types

import argparse
import os.path

import platform
import os

parser = argparse.ArgumentParser(description="Makes anything runnable.")

parser.add_argument('input', nargs=1, help='Input file')
parser.add_argument('output', nargs=1, help='Output file')
parser.add_argument('hashbang', nargs=1, help='Prepended hashbang')

args = parser.parse_args()

ifile = args.input[0]
ofile = args.output[0]
hashbang = args.hashbang[0]

tmp = ofile + ".makerunnable"

import zipapp
zipapp.create_archive(ifile, tmp, hashbang)
os.rename(tmp, ofile)
