#!/usr/bin/env python3
# -*- python -*-

import sys
import types

import argparse
import os

import py_compile

parser = argparse.ArgumentParser(description="Makes anything runnable.")

parser.add_argument('input', nargs=1, help='Input file')
parser.add_argument('output', nargs=1, help='Output file')

args = parser.parse_args()

ifile = args.input[0]
ofile = args.output[0]

tmp = ofile + ".compile-pyc"

py_compile.compile(ifile, tmp)
os.rename(tmp, ofile)
