macro(enable_torchvision)
  if(NOT BUILDSYS_DISABLE_TORCHVISION AND TARGET TorchVision::TorchVision)
    message(STATUS "Enabling TorchVision support (can be disabled by setting BUILDSYS_DISABLE_TORCHVISION variable).")
    set(TORCHVISION_FOUND ON)
  else()
    message(STATUS "Disabling TorchVision support because of BUILDSYS_DISABLE_TORCHVISION.")
    set(TORCHVISION_FOUND OFF)
  endif()
endmacro()
