find_package(GDAL REQUIRED CONFIG)

if (TARGET GDAL::GDAL)
  set(GDAL_FOUND TRUE)
  set(GDAL_LIBRARIES GDAL::GDAL)
endif()

# get_target_property(GDAL_LIBRARIES GDAL::GDAL INTERFACE_LINK_LIBRARIES)
# get_target_property(GDAL_INCLUDE_DIR GDAL::GDAL INTERFACE_INCLUDE_DIRECTORIES)