find_package(GIF CONFIG)

if (TARGET GIF::GIF)
  set(GIF_FOUND ${GIF_FOUND})
  set(GIF_VERSION ${GIF_VERSION})
  set(GIF_LIBRARIES GIF::GIF)
  get_target_property(GIF_INCLUDE_DIRS GIF::GIF INTERFACE_INCLUDE_DIRECTORIES)
  set(GIF_INCLUDE_DIR ${GIF_INCLUDE_DIRS})
endif()
